# Generated by Django 5.2.2 on 2025-06-09 21:24

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del miembro. Máximo 100 caracteres.', max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(help_text='Correo único del miembro. Se usará como identificador de contacto.', max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(help_text='Número válido en formato colombiano o internacional. Requiere código de país.', max_length=128, region='CO', verbose_name='Número de teléfono')),
                ('activo', models.BooleanField(default=True, help_text='Define si el miembro está actualmente activo en la comunidad.', verbose_name='¿Está activo?')),
                ('puede_volver', models.BooleanField(blank=True, help_text='Solo aplicable si el miembro ha sido desactivado. Indica si puede reingresar.', null=True, verbose_name='¿Puede volver?')),
                ('fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha automática en la que se registró el miembro en el sistema.', verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
