# Generated by Django 5.2.2 on 2025-06-10 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Descripción detallada del motivo de la sanción.', verbose_name='Motivo de la sanción')),
                ('fecha', models.DateField(auto_now_add=True, help_text='Fecha en la que se registró la sanción.', verbose_name='Fecha de sanción')),
                ('duracion_dias', models.PositiveIntegerField(blank=True, help_text='Duración de la sanción en días (opcional).', null=True, verbose_name='Duración (en días)')),
                ('impuesta_por', models.ForeignKey(blank=True, help_text='Usuario que registró o impuso la sanción.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sanción impuesta por')),
                ('miembro', models.ForeignKey(help_text='Miembro al que se le aplica esta sanción.', on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to='miembros.miembro', verbose_name='Miembro sancionado')),
            ],
            options={
                'verbose_name': 'Sanción',
                'verbose_name_plural': 'Sanciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
