# Generated by Django 5.2.2 on 2025-06-10 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_sancion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Detalle del error o situación que el miembro desea corregir.', verbose_name='Descripción del problema')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se envió la solicitud.', verbose_name='Fecha de solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado actual de la solicitud.', max_length=10, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, help_text='Respuesta proporcionada por el administrador (opcional).', null=True, verbose_name='Respuesta del administrador')),
                ('miembro', models.ForeignKey(help_text='Miembro que envía la solicitud de corrección.', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='miembros.miembro', verbose_name='Miembro solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de corrección',
                'verbose_name_plural': 'Solicitudes de corrección',
                'ordering': ['-fecha'],
            },
        ),
    ]
