# Generated by Django 5.2.2 on 2025-06-12 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_solicitudcorreccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='desactivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='puede_volver',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sancion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la que se registró la sanción.', verbose_name='Fecha de sanción'),
        ),
    ]
