# Generated by Django 5.2.2 on 2025-06-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_alter_miembro_activo_alter_miembro_desactivado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='puede_volver',
            field=models.BooleanField(default=True, help_text='Indica si el miembro puede ser reactivado en el futuro.', verbose_name='¿Puede volver?'),
        ),
    ]
